### ISSUE TITLE
global scope 변수 선언 이슈

### ISSUE THREAD

**Issue by RiceWorld** [pjc0247/Slacker#2]
```
string GLOBAL_TEST = "0";

[Subscribe("Global")]
public void OnHello(Message msg) {
  Slack.SendMessage(msg.channel, GLOBAL_TEST);
}
```

와 같이 global.csx 작성후 슬랙에서 응답시 Exception 발생

System.Reflection.TargetInvocationException: 호출 대상이 예외를 Throw했습니다. --->
System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.

단, 변수형을 int, long 등으로 선언시에는 이슈가 없네요.

**Comment by pjc0247** [comment]
@RiceWorld  아 죄송합니다, 가이드문서가 잘못되었네요,  아래 코드처럼 `static` 을 넣어서 작성 부탁드립니다.

``` cs
static string GLOBAL_TEST = "0";
```

또한 굳이 이렇게 하지는 않으셔도 되지만 생성자와 같은 역할을 하는 `Bootstrap`을 사용하셔도 됩니다.

``` cs
[Bootstrap]
public void OnInitialize() {
   GLOBAL_TEST = "0";
}
```

**Comment by RiceWorld** [comment]
감사합니다. static 변수 선언하니 잘되는것 같습니다.
